apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  ports:
    - port: 80            # External port to access the service
      targetPort: 3000    # Internal port of the container
      nodePort: 30000     # Custom NodePort (optional)
  selector:
    app: reactstore
